---
name: XML-XPathScript
version: 1.43
author:
  - 'Yanick Champoux <yanick@cpan.org>, Dominique Quatravaux <dom@idealx.com> and Matt Sergeant <matt@sergeant.org>'
abstract: a Perl framework for XML stylesheets
license: artistic
requires:
  Carp: 0
  Data::Dumper: 0
  File::Basename: 0
  IO::File: 0
  Scalar::Util: 0
  Symbol: 0
  XML::LibXML: 0
build_requires:
  File::Find: 0
  File::Spec: 0
provides:
  Apache::AxKit::Language::YPathScript:
    file: lib_axkit/Apache/AxKit/Language/YPathScript.pm
    version: 1.43
  XML::XPathScript::Processor:
    file: lib/XML/XPathScript/Processor.pm
    version: 1.43
  XML::XPathScript::Template:
    file: lib/XML/XPathScript/Template.pm
    version: 1.43
  XML::XPathScript::Template::Tag:
    file: lib/XML/XPathScript/Template/Tag.pm
    version: 1.43
generated_by: Module::Build version 0.2612
