---
name: XML-XPathScript
version: 1.000_001
author:
  - 'Yanick Champoux <yanick@babyl.dyndns.org>, Dominique Quatravaux <dom@idealx.com> and Matt Sergeant <matt@sergeant.org>'
abstract: a Perl framework for XML stylesheets
license: artistic
requires:
  Carp: 0
  Data::Dumper: 0
  File::Basename: 0
  IO::File: 0
  Scalar::Util: 0
  Symbol: 0
build_requires:
  File::Find: 0
  File::Spec: 0
provides:
  XML::XPathScript::Processor:
    file: lib/XML/XPathScript/Processor.pm
  XML::XPathScript::Template:
    file: lib/XML/XPathScript/Template.pm
  XML::XPathScript::Template::Tag:
    file: lib/XML/XPathScript/Template/Tag.pm
generated_by: Module::Build version 0.26
